#  docker-compose -f docker-compose.yml config check validate config
version: "2.1"
services:
  redirectphp:
    image: "	limweb/phpserv7:latest"
    container_name: redirectphp
    working_dir: /app
    restart: "always"
    ports:
      - "8080:8080"
    expose:
      - "8080"
    command: "/usr/local/bin/php /app/index.php"
    volumes:
      - ./app:/app
    labels:
      com.docker.compose.project: "redirectphp"
    environment:
      SERVER_REDIRECT: "thaifex==https://thaifexportervirtualtradeshow.com"
      DEFAULT_REDIRECT: "https://thaifexportervirtualtradeshow.com"
      # VIRTUAL_HOST: "redirectphp.local.com"
      # VIRTUAL_PORT: "8080:8080"
      # LETSENCRYPT_HOST: "redirectphp.local.com"
      # LETSENCRYPT_EMAIL: "your@email.com"
    network_mode:  "bridge"

networks:
   default:
     driver: bridge
     external:
       name: nginx-network

